# Generated by Django 3.2.7 on 2021-11-02 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='currency',
        ),
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.ManyToManyField(to='Items.Currency'),
        ),
    ]
