# Generated by Django 3.2.7 on 2021-11-02 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0002_auto_20211102_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='currency',
        ),
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Items.currency'),
        ),
    ]
