# Generated by Django 3.2.7 on 2021-11-09 07:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Items', '0005_money'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='money',
            unique_together={('user', 'money')},
        ),
    ]
