# Generated by Django 3.2.7 on 2021-11-04 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0007_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
