# Generated by Django 3.2.7 on 2021-11-04 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0008_watchlist_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='price',
        ),
    ]
