# Generated by Django 3.2.7 on 2021-11-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Traiding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='order_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'buy'), (2, 'sell')]),
        ),
    ]
