# Generated by Django 3.2.7 on 2021-11-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traiding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='order_type',
            field=models.PositiveSmallIntegerField(choices=[('buy', '1'), ('sell', '2')]),
        ),
    ]
