# Generated by Django 3.2.7 on 2021-11-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traiding', '0002_alter_offer_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='order_type',
            field=models.PositiveSmallIntegerField(choices=[('buy', 'BUY'), ('sell', 'SELL')]),
        ),
    ]
