# Generated by Django 3.2.7 on 2021-11-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traiding', '0004_alter_offer_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='order_type',
            field=models.PositiveSmallIntegerField(choices=[('1', 'buy'), ('2', 'sell')]),
        ),
    ]
